apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из ConfigMap</title>
    </head>
    <body>
      <h1>Привет от Kubernetes! Это страница из ConfigMap</h1>
      <p>Студент: Прыкин Сергей</p>
      <p>Дата: Сентябрь 2026</p>
    </body>
    </html>
