input {
  beats {
    port => 5044
    codec => json
  }
  tcp {
    port => 5000
    codec => json_lines
    type => "tcp-json"
  }
}

filter {
  if [type] != "tcp-json" {
    json {
      source => "message"
      target => "docker_log"
    }
    mutate {
      add_field => {
        "container_name" => "%{[docker_log][container_name]}"
        "container_id" => "%{[docker_log][container_id]}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
