apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
  labels:
    app: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: check-svc
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Starting DNS check for nginx-init-svc..."
          until nslookup nginx-init-svc.default.svc.cluster.local 2>&1 | grep -q "Address"; do
            echo "$(date) Waiting for nginx-init-svc..."
            sleep 3
          done
          echo "Service nginx-init-svc found! Exiting init-container."
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
